version: "3.6"

networks:
  default:
    external:
      name: network


volumes:
  ssl:

services:
  proxy-caddy:
    container_name: proxy-caddy
    build:
      context: ./
      dockerfile: build/caddy/Dockerfile
    image: registry.gitlab.com/aliasgame/caddy-proxy:2.3.0
    restart: "always"
    ports:
      - 31337:31337
      - 8443:8443
    volumes:
      - ssl:/etc/ssl
